[toolchain]
channel = "1.69"
components = [ "rustfmt", "cargo", "clippy", "rustc", "llvm-tools-preview" ]
targets = ["x86_64-apple-darwin", "x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu", "aarch64-unknown-linux-musl", "x86_64-unknown-linux-musl"]
profile = "default"
