#!/usr/bin/env bash
set -e
VERSION="3.6.0-dev"
TARGET_DIR=../../target
BUILD_DIR=$TARGET_DIR/x86_64-pc-windows-msvc/debug
CERT_NAME=logdna_dev_cert.pfx
mkdir -p "$TARGET_DIR"
CERT_PASS="$(aws s3 cp --quiet s3://ecosys-vault/$CERT_NAME.pwd /dev/stdout)"
aws s3 cp s3://ecosys-vault/$CERT_NAME "$TARGET_DIR"
#
# Sign exe files
#
mkdir -p $BUILD_DIR/signed
osslsigncode sign \
    -pkcs12 "$TARGET_DIR/$CERT_NAME" \
    -pass "$CERT_PASS" \
    -n "Mezmo Agent" \
    -i "https://www.mezmo.com" \
    -in "$BUILD_DIR/logdna-agent-svc.exe" \
    -out "$BUILD_DIR/signed/logdna-agent-svc.exe"
osslsigncode sign \
    -pkcs12 "$TARGET_DIR/$CERT_NAME" \
    -pass "$CERT_PASS" \
    -n "Mezmo Agent" \
    -i "https://www.mezmo.com" \
    -in "$BUILD_DIR/logdna-agent.exe" \
    -out "$BUILD_DIR/signed/logdna-agent.exe"
#
# Create msi
#
export VERSION
export AGENT_EXE_PATH="$BUILD_DIR/signed/logdna-agent.exe"
export AGENT_SVC_EXE_PATH="$BUILD_DIR/signed/logdna-agent-svc.exe"
export AGENT_CFG_PATH="./logdna.conf"
wixl -v --ext ui ./mezmo-agent.wxs -a x64 -o "$BUILD_DIR/mezmo-agent.msi"
#
# Sign msi
#
osslsigncode sign \
    -add-msi-dse \
    -pkcs12 "$TARGET_DIR/$CERT_NAME" \
    -pass "$CERT_PASS" \
	-n "Mezmo Agent" \
    -i "https://www.mezmo.com" \
    -t http://timestamp.comodoca.com/authenticode \
    -in "$BUILD_DIR/mezmo-agent.msi" \
    -out "$BUILD_DIR/signed/mezmo-agent.msi"

echo
echo @@@@@@  SUCCESS  @@@@@@
echo
