#!/usr/bin/env bash
set -eu
#
mkdir -p out/tools
chmod 777 out
chmod 777 out/tools
export MSI_SHA256=$(curl -sL $MSI_URL | sha256sum -b | awk "{print \$1}")
for FILE in tools/*; do 
  envsubst < $FILE > out/$FILE
done
docker run -it -v $PWD:/build -w /build chocolatey/choco choco pack -v --out /build/out mezmo-agent.nuspec





