#!/usr/bin/env bash
# shellcheck disable=SC1091
source ../msi/mk_env
# for Choco "release" package we need to use 4 part version in order to include build number
triple_only="[0-9]+\.[0-9]+\.[0-9]+"
if [[ "$BUILD_VERSION" =~ ^$triple_only$ ]]; then
# release
export BUILD_VERSION_CHOCO="$BUILD_VERSION.$BUILD_NUMBER"
else
# pre-release
export BUILD_VERSION_CHOCO="$BUILD_VERSION_FULL"
fi
