#!/usr/bin/env bash
set -eu
# shellcheck disable=SC1091
source ./mk_env
docker run -i -v $BUILD_DIR/choco:/build -w /build --env CHOCO_API_KEY="$CHOCO_API_KEY" chocolatey/choco bash << 'EOF'
set -eu
choco apikey -k $CHOCO_API_KEY -s https://push.chocolatey.org
choco push $BUILD_DIR/choco/$(cat $BUILD_DIR/choco/mezmo-agent.nupkg.name) -s https://push.chocolatey.org
EOF
echo
echo @@@@@@  SUCCESS  @@@@@@
echo
