apiVersion: v1
kind: Namespace
metadata:
  name: logdna-agent-stress-test
  labels:
    app.kubernetes.io/name: logdna-agent
    app.kubernetes.io/instance: logdna-agent
    app.kubernetes.io/version: 3.9.0-dev
