#!/usr/bin/env bash
set -eu
VER=$(sed -nE "s/^version = \"(.+)\"\$$/\1/p" ../../../bin/Cargo.toml)
export BUILD_NUMBER="${BUILD_NUMBER:-0}"
export BUILD_VERSION="${BUILD_VERSION:-"$VER+$BUILD_NUMBER"}"
export BUILD_DIR="${BUILD_DIR:-../../../target/x86_64-pc-windows-msvc/debug}"
export SRC_DIR="${SRC_DIR:-../../..}"
export CERT_NAME="${CERT_NAME:-logdna_dev_cert.pfx}"
function finish {
  rm -f "$BUILD_DIR/$CERT_NAME" "$BUILD_DIR/$CERT_NAME.pwd"
}
trap finish EXIT
#
echo build version $BUILD_VERSION
echo fetching key
aws s3 cp "s3://ecosys-vault/$CERT_NAME" "$BUILD_DIR"
aws s3 cp "s3://ecosys-vault/$CERT_NAME.pwd" "$BUILD_DIR"
./mk_msi
echo
echo @@@@@@  SUCCESS  @@@@@@
echo
