#!/usr/bin/env bash
# source root
export SRC_ROOT="${SRC_ROOT:-$(readlink -f ../../..)}"
agent_version=$(sed -nE "s/^version = \"(.+)\"\$$/\1/p" "$SRC_ROOT/bin/Cargo.toml")
export BUILD_VERSION="${BUILD_VERSION:-${agent_version}}"
export TARGET=${TARGET:-x86_64-pc-windows-msvc}
# relative to source root
export BUILD_DIR="${BUILD_DIR:-target/$TARGET/debug}"
# comes from Jenkins
export BUILD_NUMBER="${BUILD_NUMBER:-0}"
# 4th dot if any replaced by dash
BUILD_VERSION_DASH=$(echo "$BUILD_VERSION" | sed -r 's/([^\.]+\.[^\.]+\.[^\.]+)\./\1-/')
# cannot use "+" - replaced by "-build"
export BUILD_VERSION_FULL="${BUILD_VERSION_DASH}-build${BUILD_NUMBER}"
export CERT_FILE_NAME="${CERT_FILE_NAME:-mezmo_cert_debug.pfx}"
export MSI_URL="${MSI_URL:-https://logdna-agent-build-bin.s3.amazonaws.com/$BUILD_VERSION/$TARGET/signed/mezmo-agent.${BUILD_VERSION_FULL}.msi}"
