#!/usr/bin/env bash
set -eu
#
# Sign exe files
#
mkdir -p "$BUILD_DIR/signed"
echo signing exe files
osslsigncode sign \
    -pkcs12 "$BUILD_DIR/$CERT_NAME" \
    -readpass "$BUILD_DIR/$CERT_NAME.pwd" \
    -n "Mezmo Agent" \
    -h sha2 \
    -i "https://www.mezmo.com" \
    -t http://timestamp.comodoca.com/authenticode \
    -in "$BUILD_DIR/logdna-agent-svc.exe" \
    -out "$BUILD_DIR/signed/logdna-agent-svc.exe"
osslsigncode sign \
    -pkcs12 "$BUILD_DIR/$CERT_NAME" \
    -readpass "$BUILD_DIR/$CERT_NAME.pwd" \
    -n "Mezmo Agent" \
    -h sha2 \
    -i "https://www.mezmo.com" \
    -t http://timestamp.comodoca.com/authenticode \
    -in "$BUILD_DIR/logdna-agent.exe" \
    -out "$BUILD_DIR/signed/logdna-agent.exe"
#
# Create msi
#
export AGENT_VERSION=${BUILD_VERSION}
export AGENT_EXE_DIR="$BUILD_DIR/signed"
export AGENT_SRC_DIR="$SRC_DIR"
wixl -v --ext ui ./mezmo-agent.wxs -a x64 -o "$BUILD_DIR/mezmo-agent.msi"
#
# Sign msi
#
osslsigncode sign \
    -add-msi-dse \
    -pkcs12 "$BUILD_DIR/$CERT_NAME" \
    -readpass "$BUILD_DIR/$CERT_NAME.pwd" \
    -n "Mezmo Agent" \
    -h sha2 \
    -i "https://www.mezmo.com" \
    -t http://timestamp.comodoca.com/authenticode \
    -in "$BUILD_DIR/mezmo-agent.msi" \
    -out "$BUILD_DIR/signed/mezmo-agent.msi"
