#!/usr/bin/env bash
set -eu
# shellcheck disable=SC1091
source ./mk_env
export WINEPREFIX="$SRC_ROOT/$BUILD_DIR/wine"
rm -rf "$WINEPREFIX"
mkdir -p "$WINEPREFIX"
DISPLAY= WINEDEBUG=-all wine64 msiexec /qn /norestart -i "$SRC_ROOT/$BUILD_DIR/signed/mezmo-agent.msi"
MEZMO_DIR="$WINEPREFIX/drive_c/Program Files/Mezmo"
set -x
# check all files are installed
([ -f "$MEZMO_DIR/logdna-agent.exe" ] && \
[ -f "$MEZMO_DIR/logdna-agent-svc.exe" ] && \
[ -f "$MEZMO_DIR/logdna.conf.templ" ] && \
[ -f "$MEZMO_DIR/README.md" ] && \
[ -f "$MEZMO_DIR/post_install.ps1" ]) || (echo "Failed: Some files are missing!"; exit 1)
# check exe version
version=$(DISPLAY= WINEDEBUG=-all wine64 "$SRC_ROOT/$BUILD_DIR/signed/logdna-agent.exe" --version | grep LogDNA | awk '{print $3}')
[ "$version" == "$BUILD_VERSION" ] || (echo "Failed: Unexpected agent version!"; exit 1)
echo
echo @@@@@@  SUCCESS  @@@@@@
echo
