#!/bin/bash
set -e
OWN_PATH=$(readlink -f "$0")
OWN_DIR=$(dirname "$OWN_PATH")
pushd "$OWN_DIR/.."
export DOCKER_BUILDKIT=1
AWS_CREDS=$(mktemp /tmp/.aws_creds_static.XXXXXX)
echo "[default]" > "${AWS_CREDS}"
echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> "${AWS_CREDS}"
echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> "${AWS_CREDS}"
time make ARCH="${ARCH:-$(uname -m)}" AWS_SHARED_CREDENTIALS_FILE="${AWS_CREDS}" "$@"
rm "${AWS_CREDS}"
echo
echo @@@@@@  SUCCESS  @@@@@@
echo
